site_name: GAMEX
site_description: Generative AI Modeling for Extreme Events
site_url: https://gamex-network.github.io/

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top

nav:
  - Home: index.md
  - Project: project.md
  - People: people.md
  - Activities:
      - Scientific Workshop: workshop.md
      - Summer School: school.md
      - Seminar Series: seminars.md
      - Mobility: mobility.md
  - Contact: contact.md

markdown_extensions:
  - admonition
  - toc:
      permalink: false
  - tables
  - attr_list

extra:
  generator: false

plugins: []

copyright: >
  © 2026 GAMEX — Generative AI Modeling for Extreme Events.  
  Funded by <strong>Una Europa</strong> under the Seed Funding initiative.
